services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: CTR1PANEL
    ports:
    - "5432:5432"
    expose:
      - 5432
    #command: -p 5432
    #volumes: 
    #  - ./db:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CTR1PANEL"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  web:
    restart : always
    build:
      context: .
    ports:
      - 11000:11000
    expose:
      - 11000
    links:
      - "db:database"
    
    environment:
      DB_HOST: db 
      DB_PORT: 5432
      DB_NAME: CTR1PANEL
      DB_USER: postgres
      DB_PASSWORD: postgres

    depends_on:
      "db":
        condition: service_healthy
    volumes:
      - ./logs:/app/logs

    command: sh -c "sleep 5 && python app.py"